version: '3.8'

services:
  asp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asp-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - asp-bot-network

networks:
  asp-bot-network:
    driver: bridge